// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RZORp7_N9pwjp42_usVIHOPh0mv8qoA',
    appId: '1:560652645855:web:5b224a96151ba58cb8406a',
    messagingSenderId: '560652645855',
    projectId: 'polimeet-9d734',
    authDomain: 'polimeet-9d734.firebaseapp.com',
    storageBucket: 'polimeet-9d734.appspot.com',
    measurementId: 'G-ZGG92G0C4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77P_MDZp4xJc1L7mWDKCTM0WMr0dGBCs',
    appId: '1:560652645855:android:ee6d29deef8450d1b8406a',
    messagingSenderId: '560652645855',
    projectId: 'polimeet-9d734',
    storageBucket: 'polimeet-9d734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfGdkHiW6SXZRj0E7GREUsHGztAZWUPw',
    appId: '1:560652645855:ios:7222405f166d809ab8406a',
    messagingSenderId: '560652645855',
    projectId: 'polimeet-9d734',
    storageBucket: 'polimeet-9d734.appspot.com',
    iosClientId: '560652645855-ug5elbkffs08a0qv22u0qmqf5gmtq6v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.polimeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlfGdkHiW6SXZRj0E7GREUsHGztAZWUPw',
    appId: '1:560652645855:ios:7222405f166d809ab8406a',
    messagingSenderId: '560652645855',
    projectId: 'polimeet-9d734',
    storageBucket: 'polimeet-9d734.appspot.com',
    iosClientId: '560652645855-ug5elbkffs08a0qv22u0qmqf5gmtq6v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.polimeet',
  );
}
